---
abstract: 'The YAML Test Shell'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: YAML-Shell
no_index:
  directory:
    - inc
    - t
requires:
  YAML: 0.67
  perl: 5.005003
version: 0.60
